Getting JAX IPU research (most) unit tests to run on IPU model. (#62)
Github action running unit tests on IPU model. Tests using IPU hardware are skipped.
`jax-ipu-addons` has been temporarily added to the repository, until no longer required.

diff --git a/.github/workflows/jax-ipu-research-ci-internal.yaml b/.github/workflows/jax-ipu-research-ci-internal.yaml
--- a/.github/workflows/jax-ipu-research-ci-internal.yaml
+++ b/.github/workflows/jax-ipu-research-ci-internal.yaml
@@ -29,3 +29,50 @@ jobs:
         with:
           python-version: 3.8
       - uses: pre-commit/action@v3.0.0
+
+  # JAX unit tests using IPU model
+  jax_unit_tests_ipu_model:
+    runs-on: [self-hosted, Linux, X64, 20.04, Ubuntu]
+    container: graphcore/pytorch:3.1.0-ubuntu-20.04
+    timeout-minutes: 10
+    steps:
+      - name: Cancel previous
+        uses: styfle/cancel-workflow-action@0.11.0
+        with:
+          access_token: ${{ github.token }}
+        if: ${{github.ref != 'refs/head/main'}}
+      - uses: actions/checkout@v3
+      - name: Update pip
+        id: pip-cache
+        run: |
+          python3 -m pip install --upgrade pip wheel setuptools
+      # Install JAX for IPU (and addons)
+      - name: Install JAX for IPU
+        run: |
+          pip3 install -U numpy==1.23.5 scipy etils pytest
+          pip3 install https://github.com/graphcore-research/jax-experimental/releases/latest/download/jaxlib-0.3.15-cp38-none-manylinux2014_x86_64.whl
+          pip3 install https://github.com/graphcore-research/jax-experimental/releases/latest/download/jax-0.3.16-py3-none-any.whl
+          pip3 install .github/dependencies/jax_ipu_addons-0.0.1-py2.py3-none-any.whl
+      # Install other dependencies.
+      - name: Install dependencies
+        run: |
+          pip3 install -r ./requirements.txt
+          pip3 install -r ./test-requirements.txt
+      # Install repository.
+      - name: Install dependencies
+        run: |
+          python3 setup.py bdist_wheel --universal
+          pip3 install dist/*.whl
+      # Run repository unit tests.
+      - name: Run JAX IPU research unit tests
+        run: |
+          JAX_IPU_USE_MODEL=true JAX_IPU_MODEL_NUM_TILES=8 pytest --tb=short -v --log-cli-level=INFO ./tests/
+      # Dockerized workflow known to create issues with self-hosted servers.
+      # Solution is to fully cleanup the workspace for the next action.
+      # See: https://stackoverflow.com/questions/70483902/how-to-actually-clean-up-the-repository-on-self-hosted-runner-after-github-actio
+      - name: Cleanup GITHUB_WORKSPACE folder
+        run: |
+          ls -la ./
+          rm -rf ./* || true
+          rm -rf ./.??* || true
+          ls -la ./
